services:
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./sql/employees.sql:/docker-entrypoint-initdb.d/employees.sql

  redis:
    container_name: "redis"
    hostname: "redis"
    image: redis:7.0.12-alpine
    restart: always
    command: redis-server "/etc/redis/redis.conf" --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user healthcheck --pass healthcheck ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ./config/redis.conf:/etc/redis/redis.conf
